{
  "repository": {
    "name": "fabriciofx/cactoos-jdbc",
    "githubId": 132658324,
    "url": "https://github.com/fabriciofx/cactoos-jdbc",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 416171853,
      "url": "http://travis-ci.org/fabriciofx/cactoos-jdbc/builds/416171853",
      "date": "Aug 15, 2018 3:30:06 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Aug 15, 2018 3:32:07 AM",
    "reproductionDateEnd": "Aug 15, 2018 3:35:56 AM",
    "totalDuration": 225,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 3,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          3
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 152,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          152
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 12,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          12
        ]
      }
    },
    "projectRootPomPath": "./workspace/fabriciofx/cactoos-jdbc/416171853/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "tests": {
    "failingModule": "/root/workspace/fabriciofx/cactoos-jdbc/416171853",
    "overallMetrics": {
      "numberRunning": 19,
      "numberPassing": 13,
      "numberFailing": 0,
      "numberErroring": 6,
      "numberSkipping": 1,
      "failures": [
        {
          "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
          "isError": true,
          "occurrences": 5
        },
        {
          "failureName": "org.postgresql.util.PSQLException",
          "isError": true,
          "occurrences": 1
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.agenda.AgendaTest",
        "numberRunning": 3,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 3,
        "numberSkipping": 0
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.stmt.UpdateTest",
        "numberRunning": 2,
        "numberPassing": 1,
        "numberFailing": 0,
        "numberErroring": 1,
        "numberSkipping": 0
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.script.SqlScriptTest",
        "numberRunning": 2,
        "numberPassing": 1,
        "numberFailing": 0,
        "numberErroring": 1,
        "numberSkipping": 0
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.server.PgSqlServerTest",
        "numberRunning": 1,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 1,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.script.SqlScriptTest",
        "testMethod": "mysql",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.server.PgSqlServerTest",
        "testMethod": "start",
        "failureName": "org.postgresql.util.PSQLException",
        "detail": "Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.",
        "isError": true
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.stmt.UpdateTest",
        "testMethod": "longQuery",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.agenda.AgendaTest",
        "testMethod": "addContact",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.agenda.AgendaTest",
        "testMethod": "findContact",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      },
      {
        "testClass": "com.github.fabriciofx.cactoos.jdbc.agenda.AgendaTest",
        "testMethod": "renameContact",
        "failureName": "com.mysql.cj.jdbc.exceptions.CommunicationsException",
        "detail": "Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.",
        "isError": true
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "fabriciofx/cactoos-jdbc",
      "branchName": "mysql",
      "sha": "34f879c832a189f45a02fa38be2d6bee50cc5ba0",
      "url": "http://github.com/fabriciofx/cactoos-jdbc/commit/34f879c832a189f45a02fa38be2d6bee50cc5ba0",
      "date": "Aug 15, 2018 2:57:14 AM"
    }
  },
  "projectMetrics": {
    "numberModules": 1,
    "numberSourceFiles": 69,
    "numberTestFiles": 33,
    "numberLibrariesFailingModule": 28
  },
  "type": "only_fail"
}