{
  "repository": {
    "name": "nosan/embedded-cassandra",
    "githubId": 137877866,
    "url": "https://github.com/nosan/embedded-cassandra",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 441893953,
      "url": "http://travis-ci.org/nosan/embedded-cassandra/builds/441893953",
      "date": "Oct 15, 2018 11:46:34 PM"
    }
  },
  "tests": {
    "failingModule": "/root/workspace/nosan/embedded-cassandra/441893953/embedded-cassandra",
    "overallMetrics": {
      "numberRunning": 127,
      "numberPassing": 119,
      "numberFailing": 7,
      "numberErroring": 1,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "com.github.nosan.embedded.cassandra.CassandraException",
          "isError": true,
          "occurrences": 1
        },
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 7
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "numberRunning": 8,
        "numberPassing": 1,
        "numberFailing": 6,
        "numberErroring": 1,
        "numberSkipping": 0
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.artifact.RemoteArtifactTests",
        "numberRunning": 9,
        "numberPassing": 8,
        "numberFailing": 1,
        "numberErroring": 0,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "com.github.nosan.embedded.cassandra.artifact.RemoteArtifactTests",
        "testMethod": "shouldNotWorkDirectoryNotWritable",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing \"is not writable\")\n     but: an instance of java.lang.IllegalArgumentException \u003cjava.io.IOException: Could not download Cassandra from (http://127.0.0.1:37366/dist/apache-cassandra-3.11.3.zip)\u003e is a java.io.IOException\nStacktrace was: java.io.IOException: Could not download Cassandra from (http://127.0.0.1:37366/dist/apache-cassandra-3.11.3.zip)\n at com.github.nosan.embedded.cassandra.artifact.RemoteArtifact.download(RemoteArtifact.java:184)\n at com.github.nosan.embedded.cassandra.artifact.RemoteArtifact.get(RemoteArtifact.java:106)\n at com.github.nosan.embedded.cassandra.artifact.RemoteArtifactTests.shouldNotWorkDirectoryNotWritable(RemoteArtifactTests.java:102)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\n at com.github.nosan.embedded.cassandra.testutil.Output$1.evaluate(Output.java:55)\n at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at com.github.nosan.embedded.cassandra.testutil.WebServer$1.evaluate(WebServer.java:60)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.FileNotFoundException: http://127.0.0.1:37366/dist/apache-cassandra-3.11.3.zip\n at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\n at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\n at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n at java.lang.reflect.Constructor.newInstance(Constructor.java:423)\n at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)\n at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)\n at java.security.AccessController.doPrivileged(Native Method)\n at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)\n at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)\n at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)\n at com.github.nosan.embedded.cassandra.artifact.RemoteArtifact.download(RemoteArtifact.java:179)\n ... 32 more\nCaused by: java.io.FileNotFoundException: http://127.0.0.1:37366/dist/apache-cassandra-3.11.3.zip\n at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)\n at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)\n at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)\n at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)\n at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)\n at com.github.nosan.embedded.cassandra.artifact.RemoteArtifact.download(RemoteArtifact.java:161)\n ... 32 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "invalidConfigurationNoTransport",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of com.github.nosan.embedded.cassandra.CassandraException and exception with cause expects type \u003cclass java.io.IOException\u003e and a message \"invalid_property\")\n     but: exception with cause expects type \u003cclass java.io.IOException\u003e and a message \"invalid_property\" cause was \u003cjava.io.IOException: Cassandra has not be started. Please see logs for more details.\n\u003e\nStacktrace was: com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra\n at com.github.nosan.embedded.cassandra.local.LocalCassandraDelegate.start(LocalCassandraDelegate.java:116)\n at com.github.nosan.embedded.cassandra.testutil.CassandraRunner.run(CassandraRunner.java:49)\n at com.github.nosan.embedded.cassandra.local.AbstractLocalCassandraTests.invalidConfigurationNoTransport(AbstractLocalCassandraTests.java:102)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at com.github.nosan.embedded.cassandra.testutil.Output$1.evaluate(Output.java:55)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Cassandra has not be started. Please see logs for more details.\n\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.throwException(LocalCassandra.java:240)\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.start(LocalCassandra.java:116)\n at com.github.nosan.embedded.cassandra.local.LocalCassandraDelegate.start(LocalCassandraDelegate.java:103)\n ... 29 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "onlyRpc",
        "failureName": "java.lang.AssertionError",
        "detail": "Cassandra has failed (com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra) - (java.io.IOException: Cassandra has not be started. Please see logs for more details.\n)",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "jvmOptions",
        "failureName": "java.lang.AssertionError",
        "detail": "Cassandra has failed (com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra) - (java.io.IOException: Cassandra has not be started. Please see logs for more details.\n)",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "noTransport",
        "failureName": "java.lang.AssertionError",
        "detail": "Cassandra has failed (com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra) - (java.io.IOException: Cassandra has not be started. Please see logs for more details.\n)",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "invalidConfiguration",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of com.github.nosan.embedded.cassandra.CassandraException and exception with cause expects type \u003cclass java.io.IOException\u003e and a message \"invalid_property\")\n     but: exception with cause expects type \u003cclass java.io.IOException\u003e and a message \"invalid_property\" cause was \u003cjava.io.IOException: Cassandra has not be started. Please see logs for more details.\n\u003e\nStacktrace was: com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra\n at com.github.nosan.embedded.cassandra.local.LocalCassandraDelegate.start(LocalCassandraDelegate.java:116)\n at com.github.nosan.embedded.cassandra.testutil.CassandraRunner.run(CassandraRunner.java:49)\n at com.github.nosan.embedded.cassandra.local.AbstractLocalCassandraTests.invalidConfiguration(AbstractLocalCassandraTests.java:92)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at com.github.nosan.embedded.cassandra.testutil.Output$1.evaluate(Output.java:55)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Cassandra has not be started. Please see logs for more details.\n\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.throwException(LocalCassandra.java:240)\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.lambda$start$0(LocalCassandra.java:100)\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.await(LocalCassandra.java:214)\n at com.github.nosan.embedded.cassandra.local.LocalCassandra.start(LocalCassandra.java:98)\n at com.github.nosan.embedded.cassandra.local.LocalCassandraDelegate.start(LocalCassandraDelegate.java:103)\n ... 29 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "restart",
        "failureName": "com.github.nosan.embedded.cassandra.CassandraException",
        "detail": "Unable to start Cassandra",
        "isError": true
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.local.LocalCassandraV_3_11_3_Tests",
        "testMethod": "several",
        "failureName": "java.lang.AssertionError",
        "detail": "Cassandra has failed (com.github.nosan.embedded.cassandra.CassandraException: Unable to start Cassandra) - (java.io.IOException: Cassandra has not be started. Please see logs for more details.\n)",
        "isError": false
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "nosan/embedded-cassandra",
      "branchName": "1.0.0",
      "sha": "ce69cf746388e190ad7a910e9eb683fe82271d66",
      "url": "http://github.com/nosan/embedded-cassandra/commit/ce69cf746388e190ad7a910e9eb683fe82271d66",
      "date": "Oct 15, 2018 11:42:51 PM"
    }
  },
  "projectMetrics": {
    "numberModules": 1,
    "numberSourceFiles": 44,
    "numberTestFiles": 40,
    "numberLibrariesFailingModule": 28
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Oct 15, 2018 11:59:42 PM",
    "reproductionDateEnd": "Oct 16, 2018 12:03:03 AM",
    "totalDuration": 197,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 3,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          3
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 27,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          27
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 103,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          103
        ]
      }
    },
    "projectRootPomPath": "./workspace/nosan/embedded-cassandra/441893953/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "type": "only_fail"
}