-------------------------------------------------------------------------------
Test set: jmri.util.exceptionhandler.UncaughtExceptionHandlerTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.524 s <<< FAILURE! - in jmri.util.exceptionhandler.UncaughtExceptionHandlerTest
testThread(jmri.util.exceptionhandler.UncaughtExceptionHandlerTest)  Time elapsed: 1.386 s  <<< FAILURE!
java.lang.AssertionError: No message present: Uncaught Exception caught by jmri.util.exceptionhandler.UncaughtExceptionHandler
	at org.junit.Assert.fail(Assert.java:88)
	at jmri.util.JUnitAppender.assertErrorMessage(JUnitAppender.java:223)
	at jmri.util.exceptionhandler.UncaughtExceptionHandlerTest.testThread(UncaughtExceptionHandlerTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.extensions.jfcunit.JFCTestCase$5.run(JFCTestCase.java:580)
	at junit.extensions.jfcunit.JFCTestCase$3.run(JFCTestCase.java:478)
	at java.lang.Thread.run(Thread.java:745)

