<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" name="redis.clients.jedis.tests.JedisPoolTest" time="0.049" tests="22" errors="17" skipped="0" failures="0">
  <properties>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.121-b13"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="/root/workspace/xetorthio/jedis/387367291"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="skip.gulp" value="true"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="findbugs.skip" value="true"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/root/workspace/xetorthio/jedis/387367291"/>
    <property name="checkstyle.skip" value="true"/>
    <property name="java.runtime.version" value="1.8.0_121-8u121-b13-1~bpo8+1-b13"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="skip.npm" value="true"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="gpg.skip" value="true"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="cobertura.skip" value="true"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="license.skip" value="true"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="skip.bower" value="true"/>
    <property name="maven.repo.local" value="/root/./workspace/xetorthio/jedis/387367291/.m2"/>
    <property name="os.version" value="3.10.0-862.3.2.el7.x86_64"/>
    <property name="user.home" value="/root"/>
    <property name="user.timezone" value="Europe/Paris"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="user.name" value="root"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.5.2.jar"/>
    <property name="skipITs" value="true"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher -B -D enforcer.skip=true -D dependency-check.skip=true -D skipITs=true -D cobertura.skip=true -D maven.repo.local=/root/./workspace/xetorthio/jedis/387367291/.m2 -D rat.skip=true -D findbugs.skip=true -D skip.bower=true -D gpg.skip=true -D checkstyle.skip=true -D skip.gulp=true -D license.skip=true -D skip.npm=true test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="dependency-check.skip" value="true"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_121"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="enforcer.skip" value="true"/>
    <property name="rat.skip" value="true"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase name="checkJedisIsReusedWhenReturned" classname="redis.clients.jedis.tests.JedisPoolTest" time="0">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkJedisIsReusedWhenReturned(JedisPoolTest.java:70)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkJedisIsReusedWhenReturned(JedisPoolTest.java:70)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkJedisIsReusedWhenReturned(JedisPoolTest.java:70)
</error>
  </testcase>
  <testcase name="checkPoolRepairedWhenJedisIsBroken" classname="redis.clients.jedis.tests.JedisPoolTest" time="0">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolRepairedWhenJedisIsBroken(JedisPoolTest.java:86)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolRepairedWhenJedisIsBroken(JedisPoolTest.java:86)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolRepairedWhenJedisIsBroken(JedisPoolTest.java:86)
</error>
  </testcase>
  <testcase name="getNumActiveIsNegativeWhenPoolIsClosed" classname="redis.clients.jedis.tests.JedisPoolTest" time="0"/>
  <testcase name="testCloseConnectionOnMakeObject" classname="redis.clients.jedis.tests.JedisPoolTest" time="0">
    <error message="Failed connecting to host localhost:6379" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.testCloseConnectionOnMakeObject(JedisPoolTest.java:378)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.testCloseConnectionOnMakeObject(JedisPoolTest.java:378)
</error>
  </testcase>
  <testcase name="selectDatabaseOnActivation" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.selectDatabaseOnActivation(JedisPoolTest.java:186)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.selectDatabaseOnActivation(JedisPoolTest.java:186)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.selectDatabaseOnActivation(JedisPoolTest.java:186)
</error>
  </testcase>
  <testcase name="returnResourceDestroysResourceOnException" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002"/>
  <testcase name="returnResourceShouldResetState" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.returnResourceShouldResetState(JedisPoolTest.java:276)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.returnResourceShouldResetState(JedisPoolTest.java:276)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.returnResourceShouldResetState(JedisPoolTest.java:276)
</error>
  </testcase>
  <testcase name="checkCloseableConnections" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.001">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkCloseableConnections(JedisPoolTest.java:45)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkCloseableConnections(JedisPoolTest.java:45)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkCloseableConnections(JedisPoolTest.java:45)
</error>
  </testcase>
  <testcase name="checkPoolOverflow" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002">
    <error message="Unexpected exception, expected&lt;redis.clients.jedis.exceptions.JedisExhaustedPoolException&gt; but was&lt;redis.clients.jedis.exceptions.JedisConnectionException&gt;" type="java.lang.Exception"><![CDATA[java.lang.Exception: Unexpected exception, expected<redis.clients.jedis.exceptions.JedisExhaustedPoolException> but was<redis.clients.jedis.exceptions.JedisConnectionException>
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolOverflow(JedisPoolTest.java:105)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolOverflow(JedisPoolTest.java:105)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkPoolOverflow(JedisPoolTest.java:105)
]]></error>
  </testcase>
  <testcase name="getNumActiveReturnsTheCorrectNumber" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.getNumActiveReturnsTheCorrectNumber(JedisPoolTest.java:341)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.getNumActiveReturnsTheCorrectNumber(JedisPoolTest.java:341)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.getNumActiveReturnsTheCorrectNumber(JedisPoolTest.java:341)
</error>
  </testcase>
  <testcase name="startWithUrlString" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.001">
    <error message="Failed connecting to host localhost:6380" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6380
	at redis.clients.jedis.tests.JedisPoolTest.startWithUrlString(JedisPoolTest.java:149)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.startWithUrlString(JedisPoolTest.java:149)
</error>
  </testcase>
  <testcase name="allowUrlWithNoDBAndNoPassword" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.003"/>
  <testcase name="nonDefaultDatabase" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.003">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.nonDefaultDatabase(JedisPoolTest.java:130)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.nonDefaultDatabase(JedisPoolTest.java:130)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.nonDefaultDatabase(JedisPoolTest.java:130)
</error>
  </testcase>
  <testcase name="checkConnections" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.002">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkConnections(JedisPoolTest.java:33)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkConnections(JedisPoolTest.java:33)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkConnections(JedisPoolTest.java:33)
</error>
  </testcase>
  <testcase name="testAddObject" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.003">
    <error message="Error trying to add idle objects" type="redis.clients.jedis.exceptions.JedisException">redis.clients.jedis.exceptions.JedisException: Error trying to add idle objects
	at redis.clients.jedis.tests.JedisPoolTest.testAddObject(JedisPoolTest.java:367)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.testAddObject(JedisPoolTest.java:367)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.testAddObject(JedisPoolTest.java:367)
</error>
  </testcase>
  <testcase name="startWithUrl" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.001">
    <error message="Failed connecting to host localhost:6380" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6380
	at redis.clients.jedis.tests.JedisPoolTest.startWithUrl(JedisPoolTest.java:161)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.startWithUrl(JedisPoolTest.java:161)
</error>
  </testcase>
  <testcase name="customClientName" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.003">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.customClientName(JedisPoolTest.java:208)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.customClientName(JedisPoolTest.java:208)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.customClientName(JedisPoolTest.java:208)
</error>
  </testcase>
  <testcase name="checkResourceIsCloseable" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.006">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkResourceIsCloseable(JedisPoolTest.java:304)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkResourceIsCloseable(JedisPoolTest.java:304)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkResourceIsCloseable(JedisPoolTest.java:304)
</error>
  </testcase>
  <testcase name="shouldThrowInvalidURIExceptionForInvalidURI" classname="redis.clients.jedis.tests.JedisPoolTest" time="0"/>
  <testcase name="securePool" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.004">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.securePool(JedisPoolTest.java:119)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.securePool(JedisPoolTest.java:119)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.securePool(JedisPoolTest.java:119)
</error>
  </testcase>
  <testcase name="returnNullObjectShouldNotFail" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.001"/>
  <testcase name="checkConnectionWithDefaultPort" classname="redis.clients.jedis.tests.JedisPoolTest" time="0.005">
    <error message="Could not get a resource from the pool" type="redis.clients.jedis.exceptions.JedisConnectionException">redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.jedis.tests.JedisPoolTest.checkConnectionWithDefaultPort(JedisPoolTest.java:57)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Failed connecting to host localhost:6379
	at redis.clients.jedis.tests.JedisPoolTest.checkConnectionWithDefaultPort(JedisPoolTest.java:57)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.tests.JedisPoolTest.checkConnectionWithDefaultPort(JedisPoolTest.java:57)
</error>
  </testcase>
</testsuite>