-------------------------------------------------------------------------------
Test set: com.oneandone.ejbcdiunit.persistencefactory.MySqlTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 44.243 sec <<< FAILURE! - in com.oneandone.ejbcdiunit.persistencefactory.MySqlTest
test(com.oneandone.ejbcdiunit.persistencefactory.MySqlTest)  Time elapsed: 42.055 sec  <<< ERROR!
org.jboss.weld.exceptions.WeldException: WELD-000049 Unable to invoke [method] @PostConstruct public com.oneandone.ejbcdiunit.helpers.MySqlStarter.create() on com.oneandone.ejbcdiunit.helpers.MySqlStarter@2bb62414
Caused by: java.lang.reflect.InvocationTargetException
Caused by: ch.vorburger.exec.ManagedProcessException: An error occurred while starting the database
Caused by: ch.vorburger.exec.ManagedProcessException: 
Asked to wait for "mysqld: ready for connections." from Program [/tmp/MariaDB4j/base/bin/mysqld, --no-defaults, --console, --skip-grant-tables, --max_allowed_packet=64M, --basedir=/tmp/MariaDB4j/base, --datadir=/tmp/MariaDB4j/data/3406, --port=3406, --socket=/tmp/MariaDB4j.3406.sock] (in working directory /tmp/MariaDB4j/base), but it already exited! (without that message in console), last 100 lines of console:
2018-06-07 17:15:32 140592819505024 [Note] /tmp/MariaDB4j/base/bin/mysqld (mysqld 10.1.13-MariaDB) starting as process 5597 ...
2018-06-07 17:15:32 140592819505024 [ERROR] Fatal error: Please consult the Knowledge Base to find out how to run mysqld as root!

2018-06-07 17:15:32 140592819505024 [ERROR] Aborting


test2(com.oneandone.ejbcdiunit.persistencefactory.MySqlTest)  Time elapsed: 0.267 sec
