-------------------------------------------------------------------------------
Test set: io.atomix.core.AtomixTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 109.17 sec <<< FAILURE!
testClientMetadata(io.atomix.core.AtomixTest)  Time elapsed: 1.039 sec  <<< ERROR!
java.util.concurrent.ExecutionException: io.atomix.utils.config.ConfigurationException: Duplicate system group detected
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.updatePartitionGroups(DefaultPartitionGroupMembershipService.java:248)
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.lambda$bootstrap$7(DefaultPartitionGroupMembershipService.java:223)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

testScaleUpPersistent(io.atomix.core.AtomixTest)  Time elapsed: 12.171 sec  <<< ERROR!
java.util.concurrent.ExecutionException: io.atomix.utils.config.ConfigurationException: Duplicate system group detected
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.updatePartitionGroups(DefaultPartitionGroupMembershipService.java:248)
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.lambda$bootstrap$7(DefaultPartitionGroupMembershipService.java:223)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

testScaleDownPersistent(io.atomix.core.AtomixTest)  Time elapsed: 36.035 sec  <<< ERROR!
java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:5003
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)

testClientJoinLeaveConsensus(io.atomix.core.AtomixTest)  Time elapsed: 0.544 sec  <<< ERROR!
java.util.concurrent.ExecutionException: io.atomix.utils.config.ConfigurationException: Duplicate system group detected
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.updatePartitionGroups(DefaultPartitionGroupMembershipService.java:248)
	at io.atomix.primitive.partition.impl.DefaultPartitionGroupMembershipService.lambda$bootstrap$7(DefaultPartitionGroupMembershipService.java:223)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

testScaleUpEphemeral(io.atomix.core.AtomixTest)  Time elapsed: 1.019 sec  <<< ERROR!
java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /127.0.0.1:5003
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)

